server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          url: https://github.com/juankll2/microservicios_web.git
          searchPaths: config-data
          user: ${GIT_USER}
          password: ${GIT_PASSWORD}
  security:
    user:
      name: root
      password: s3cr3t

